version: '3'

services:
  app:
    build: .
    container_name: nestjs_app
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/mydatabase?retryWrites=true&w=majority
      - DB_NAME=mydatabase
      - PORT=3000
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 en el host
    volumes:
      - .:/app
    restart: always
